name: CI  FinTrack

on:
  push:
    branches: [ "master", "entrega-intermediaria" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar o projeto
        run: mvn compile --no-transfer-progress

      - name: Executar todos os testes (unitários + integração)
        run: mvn test --no-transfer-progress

      - name: Gerar JAR executável
        run: mvn package -DskipTests --no-transfer-progress

      - name: Upload do JAR como artefato
        uses: actions/upload-artifact@v4
        with:
          name: fintrack-jar
          path: target/fintrack.jar
